### ISSUE TITLE
Container image repository lifecycle management

### ISSUE THREAD

**Issue by paulbes** [oslokommune/okctl#415]
This issue follows from a discussion with @yngvark and @deifyed, where we were trying to agree on what approach to take. There is probably missing some details towards the end. 

With `okctl`, the aim is to be opinionated and assist the user whenever possible. However, we want to do so without overloading the user cognitively, i.e., provide them with as few and manageable options as possible. The question we are debating is to what degree this statement is true:

> As a user, I want `okctl` to assist with the lifecycle management of container repositories

# Container image repository lifecycle management

Creating an [AWS Elastic Container Registry](https://docs.aws.amazon.com/AmazonECR/latest/userguide/what-is-ecr.html) repository and making it available for use includes the set of tasks listed below. As always, getting these settings right may be non-trivial, depending on the experience of the users.

> Amazon Elastic Container Registry (Amazon ECR) is an AWS-managed container image registry service that is secure, scalable, and reliable. Amazon ECR supports private container image repositories with resource-based permissions using AWS IAM. This is so that specified users or Amazon EC2 instances can access your container repositories and images. You can use your preferred CLI to push, pull, and manage Docker images, Open Container Initiative (OCI) images, and OCI compatible artifacts.

1. Create a private repository

When creating a repository, the recommended configuration is as follows:

```yaml
AppRepository: 
  Type: AWS::ECR::Repository
  Properties: 
    RepositoryName: "app/repository"
    ImageScanningConfiguration: 
      ScanOnPush: "true"
   ImageTagMutability: "IMMUTABLE"
```

Image tags should be **immutable**, so it is easier to rollback in case of a bad deployment. Mutable tags are also a [security risk](https://sysdig.com/blog/toctou-tag-mutability/). Finally, when working with declarative deployments, as we do with [ArgoCD](https://argoproj.github.io/argo-cd) this will not work.

We also want to enable [scanning the images](https://docs.aws.amazon.com/AmazonECR/latest/userguide/image-scanning.html) for vulnerabilities on each push. It is an easy way to ensure that we do not deploy container images with known security vulnerabilities.

We probably want to add a [repository lifecycle policy](https://docs.aws.amazon.com/AmazonECR/latest/userguide/LifecyclePolicies.html) as well, where we keep the last _N_ images (sorted by age, keep the newest).

2. Update the IAM policy of a service user

We take ownership of a service user; currently, we have requested creating an `okctl-service-user` in all AWS accounts. This service user is reserved for use with `okctl`. We try to follow the pattern of [least privileges](https://en.wikipedia.org/wiki/Principle_of_least_privilege), particularly when we export AWS access credentials to an external service; Github in this particular case. Therefore this user should be limited to writing images only to the ECR repositories we have created. This means that when we add an ECR repository to an AWS account, we also need to update the service user's IAM policy to reflect this change.

3. Push an image to the ECR repository

At some point in time, we will build our first container image. We need to push this image to ECR, which means we need to fetch docker login credentials compatible with ECR, tag the image with the [ECR URL](https://docs.aws.amazon.com/AmazonECR/latest/userguide/docker-push-ecr-image.html), and upload the built image. 

4. Retrieve the image details

After the image has been pushed to ECR, we need to retrieve the [image details](https://docs.aws.amazon.com/AmazonECR/latest/userguide/image-info.html), though we should probably return an error if the security scanning failed. If the scan didn't fail, we could return the complete image URL with the sha256 digest.

5. Update the deployment with the `repository/app@digest`

Finally, we can update our deployment, probably with a [kustomize](https://kustomize.io) patch or similar. 

6. Deploy our new image

This we do by pushing the image to git and then let ArgoCD deploy the new image.

# Integrating lifecycle management with okctl

Should we assist with the lifecycle management of container image repositories? If the task is sufficiently complicated for the end-user, then yes, we probably should. It follows the mantra of [difficult for us, easy for them](http://www.whatwilliamsaid.com/2019/07/difficult-for-us-easy-for-them/). Given some non-obvious pitfalls, e.g., image tag mutability, image scan result, IAM access policy, etc., we should take it upon ourselves to create mechanisms that alleviate the load on the end-user.

## How should we assist?

Here comes the difficult part, though we have a mechanism that **we believe in**: the [declarative](https://blog.nelhage.com/post/declarative-configuration-management/) approach. 

### Extending the `cluster.yaml`

We start by declaring the repositories in our `cluster` file:

```yaml
metadata:
  name: myCluster
repositories:
- myapp/frontend
- myapp/backend
- myapp/backend-migrations
```

Each repository listed above will expand to the following pattern when referencing a particular image:

**aws_account_id**.dkr.ecr.**region**.amazonaws.com/myapp/backend@sha256:eda364...FAKE

In some way, we want to reference these image repositories in our Deployment, ReplicaSets or Pods, could be as easy as using the name directly:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: myapp/backend # <- just like so
        ports:
        - containerPort: 80
```

We can then expand these to their full URL, with the digest, by parsing the YAML files, searching for the repositories in question, and building a `kustomize` patch that replaces the image.

We could do this with a command:

```bash
$ okctl deploy ...
```

Alternatively, we could return some basic information about the image location:

```bash
$ okctl show repository ENV REPOSITORY_NAME
```

**Comment by deifyed** [comment]
My argument is the following:
One application should have one ECR repository created by default. I believe this will suit 80% of all the use cases. By supporting multiple ECR repositories per application, we force cognitive load upon the majority due to the needs of the few. 

We have the chance here to save the user from having to manage their ECR repositories by creating a repository on `apply application` without requiring any configuration. We also save them from having to maintain this list over the course of time.

In the event someone needs multiple images for a single application, be it init containers or sidecars, we can support them and/or write documentation on how to create them manually.

I think its extremely important that we are vigilant in choosing what cases we should support or which ones we should not support. We _can_ make everything declaratively adjustable, but do we want to create `okterraform`? If a frankenstein between `kubectl` and `terraform` is the goal here, sure, I'll code. But is that really what we want?

**Comment by yngvark** [comment]
> Update the deployment with the repository/app@digest

okctl apply application already creates the deployment.yaml and the other k8s resources. I see no need to make these resources pretty, i.e. replacing the actual ECR image tag with a shortened one. What needs to be pretty is application.yaml (the output of okctl scaffold application). Making deployment.yaml pretty for then to patch it makes is too much magic which I think will just confuse the user. So I suggest to let deployment.yaml contain the `image:aws_account_id.dkr.ecr.region.amazonaws.com/myapp/backend@sha256:eda364...`.

> Extending the cluster.yaml

We already have application.yaml (okctl scaffold cluster) for containing application specific input from the user, why not put the repositories declaration there? I see no argumenet above for putting it in cluster.yaml.

**Comment by deifyed** [comment]
Good points.

I agree that the k8s resources dont need to be pretty, but the `cluster.yaml` and `application.yaml` should be. That means the users get a nice interface to handle things with, and that moving past the pretty interface will lead them directly to the plumbing.

**Comment by deifyed** [comment]
I just realized; I think the premise here is erronous.

> ... The question we are debating is to what degree this statement is true:
> As a user, I want okctl to assist with the lifecycle management of container repositories

Just to be clear, I never intended to argue against this. My arguments are about how we implement this assistance, as in how much assistance and and how much assistance we should deliver in `okctl` as a whole.

I definitely agree that there is a place for ECR / container repositories in `okctl`.

**Comment by paulbes** [comment]
I was trying to go broader than our initial discussion, should probably have clarified that!  So just to be clear, the discussion was primarily supposed to be about _how_ to assist with creating repositories.

Just to update the discussion, we have agreed on doing this in the `application.yaml` file, and we will user-test the format before finalising the implementation.
 
Perhaps we can close this issue then? Maybe use some of the discussion here in the documentation though

**Comment by yngvark** [comment]
Suggestion for format of application.yaml:

# Use cases

## Use case: Image in ECR

application.yaml:

```yaml
images:
  - name: my-app  
```

Resulting deployment.yaml:

```yaml
kind: Deployment
spec:
  template:
    spec:
      containers:
      - name: my-app
        image: 123456789012.dkr.ecr.eu-west-1.amazonaws.com/my-app
```

## Use case: Existing image

application.yaml:

```yaml
images:
  - name: helloworld
    image: karthequian/helloworld
```

Resulting deployment.yaml:

```yaml
kind: Deployment
spec:
  template:
    spec:
      containers:
      - name: helloworld
        image: karthequian/helloworld
```

## Use case: Two images

Second image could be a sidecar, or anything else.

application.yaml:

```yaml
images:
  - name: my-app
  - name: my-other-image
```

Resulting deployment.yaml:

```yaml
kind: Deployment
spec:
  template:
    spec:
      containers:
      - name: my-app
        image: 123456789012.dkr.ecr.eu-west-1.amazonaws.com/my-app
      - name: my-other-image
        image: 123456789012.dkr.ecr.eu-west-1.amazonaws.com/my-other-image
```

## Use case: Image in ECR and existing image

application.yaml:

```yaml
images:
  - name: my-app
  - name: postgres
    image: postgres:13:2
```

Resulting deployment.yaml:

```yaml
kind: Deployment
spec:
  template:
    spec:
      containers:
      - name: my-app
        image: 123456789012.dkr.ecr.eu-west-1.amazonaws.com/my-app
      - name: postgres
        image: postgres:13.2
```

# Full example

Just to give more context, here are non-shortened versions of application.yaml and deployment.yaml.

## application.yaml

```yaml
# A name that identifies your app
name: my-app
# The images your application uses
images:
  - name: my-app
  - name: postgres
    image: bitnami/postgresql:13.2.0

# The version of your app which is available as an image
version: 0.0.1
# The Kubernetes namespace where your app will live
namespace: my-namespace

# The subdomain of the URL your app should be available on
# Example in a cluster with yktesting.oslo.systems as root cluster URL (as defined by primary DNS zone in the
# cluster declaration):
#
# subDomain: okctl
# result: okctl.yktesting.oslo.systems
# Comment this out to avoid setting up an ingress, in other words - avoid exposing it on the internet
#
subDomain: my-app

# The port your app listens on
# Comment this out to avoid setting up a service (required if url is specified)
#
port: 3000

# How many replicas of your application should we scaffold
#replicas: 3 # 1 by default

# A Docker repository secret for pulling your image
#imagePullSecret: my-pull-secret-name

# The environment your app requires
#environment:
#  MY_VARIABLE: my-value

# Volumes to mount
#volumes:
#  - /path/to/mount/volume: # Requests 1Gi by default
#  - /path/to/mount/volume: 24Gi

# Annotations for your ingress
#ingress:
#  annotations:
#    nginx.ingress.kubernetes.io/cors-allow-origin: http://localhost:8080
#    cert-manager.io/cluster-issuer: letsencrypt-production
```

## deployment.yaml

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: 123456789012.dkr.ecr.eu-west-1.amazonaws.com/my-app
      - name: postgres
        image: bitnami/postgresql:13.2.0
```
